
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign,ba=aa({},e),k=(a,b)=>{throw b;},ca="object"===typeof window,l="function"===typeof importScripts,t="",da,u,v,fs,w,ea;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)t=l?require("path").dirname(t)+"/":__dirname+"/",ea=()=>{w||(fs=require("fs"),w=require("path"))},da=function(a,b){ea();a=w.normalize(a);return fs.readFileSync(a,b?null:"utf8")},v=a=>{a=da(a,!0);a.buffer||(a=new Uint8Array(a));return a},u=(a,b,c)=>{ea();a=w.normalize(a);fs.readFile(a,function(d,f){d?c(d):b(f.buffer)})},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),
"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",function(a){if(!(a instanceof x))throw a;}),process.on("unhandledRejection",function(a){throw a;}),k=(a,b)=>{if(noExitRuntime||0<fa)throw process.exitCode=a,b;b instanceof x||y("exiting due to exception: "+b);process.exit(a)},e.inspect=function(){return"[Emscripten Module object]"};else if(ca||l)l?t=self.location.href:"undefined"!==typeof document&&document.currentScript&&(t=document.currentScript.src),t=0!==t.indexOf("blob:")?
t.substr(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1):"",da=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};e.print||console.log.bind(console);
var y=e.printErr||console.warn.bind(console);aa(e,ba);ba=null;e.quit&&(k=e.quit);var z;e.wasmBinary&&(z=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var ha,ia=!1;
function ja(a,b,c){var d={string:function(n){var p=0;if(null!==n&&void 0!==n&&0!==n){var r=(n.length<<2)+1;p=ka(r);B(n,p,r)}return p},array:function(n){var p=ka(n.length);la.set(n,p);return p}};a=e["_"+a];var f=[],h=0;if(c)for(var g=0;g<c.length;g++){var m=d[b[g]];m?(0===h&&(h=ma()),f[g]=m(c[g])):f[g]=c[g]}b=a.apply(null,f);b=function(n){0!==h&&na(h);return n}(b)}var oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function C(a,b){if(a){var c=D,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&oa)a=oa.decode(c.subarray(a,b));else{for(d="";a<b;){var f=c[a++];if(f&128){var h=c[a++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var g=c[a++]&63;f=224==(f&240)?(f&15)<<12|h<<6|g:(f&7)<<18|h<<12|g<<6|c[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}a=d}}else a="";return a}
function B(a,b,c){var d=D;if(!(0<c))return 0;var f=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-f}var la,D,pa,qa,E,ra,sa,F,ta,ua=[],va=[],wa=[],xa=[],ya=[],fa=0;
function za(){var a=e.preRun.shift();ua.unshift(a)}var G=0,Aa=null,H=null;e.preloadedImages={};e.preloadedAudios={};function A(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";y(a);ia=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ba(){return I.startsWith("data:application/octet-stream;base64,")}var I;I="pacman.wasm";if(!Ba()){var Ca=I;I=e.locateFile?e.locateFile(Ca,t):t+Ca}
function Da(){var a=I;try{if(a==I&&z)return new Uint8Array(z);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function Ea(){if(!z&&(ca||l)){if("function"===typeof fetch&&!I.startsWith("file://"))return fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return Da()});if(u)return new Promise(function(a,b){u(I,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Da()})}
function K(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.nc;"number"===typeof c?void 0===b.Nb?L(c)():L(c)(b.Nb):c(void 0===b.Nb?null:b.Nb)}}}function L(a){return ta.get(a)}var Fa=0;function Ga(){for(var a=M.length-1;0<=a;--a)Ha(a);M=[];N=[]}var N=[];function Ia(){if(Fa&&Ja.Ib)for(var a=0;a<N.length;++a){var b=N[a];N.splice(a,1);--a;b.vc.apply(null,b.kc)}}var M=[];function Ha(a){var b=M[a];b.target.removeEventListener(b.Bb,b.ec,b.Cb);M.splice(a,1)}
function O(a){function b(d){++Fa;Ja=a;Ia();a.Eb(d);Ia();--Fa}if(a.Db)a.ec=b,a.target.addEventListener(a.Bb,b,a.Cb),M.push(a),Ka||(xa.push(Ga),Ka=!0);else for(var c=0;c<M.length;++c)M[c].target==a.target&&M[c].Bb==a.Bb&&Ha(c--)}function La(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var Ka,Ja,Ma,Na,P,Oa,Pa,Qa,Ra,Sa=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function Q(a){a=2<a?C(a):a;return Sa[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function Ta(a){return 0>Sa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function Ua(a,b,c,d,f,h){Ma||(Ma=R(256));a={target:Q(a),Bb:h,Db:d,Eb:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Ma;B(La(g.target),n+0,128);B(m,n+128,128);L(d)(f,n,b)&&g.preventDefault()},Cb:c};O(a)}
function Va(a,b,c,d,f,h){Na||(Na=R(176));a={target:Q(a),Ib:!0,Bb:h,Db:d,Eb:function(g){var m=Na;F[m>>3]=g.timeStamp;var n=m>>2;E[n+2]=g.location;E[n+3]=g.ctrlKey;E[n+4]=g.shiftKey;E[n+5]=g.altKey;E[n+6]=g.metaKey;E[n+7]=g.repeat;E[n+8]=g.charCode;E[n+9]=g.keyCode;E[n+10]=g.which;B(g.key||"",m+44,32);B(g.code||"",m+76,32);B(g.char||"",m+108,32);B(g.locale||"",m+140,32);L(d)(f,m,b)&&g.preventDefault()},Cb:c};O(a)}
function Wa(a,b,c){F[a>>3]=b.timeStamp;a>>=2;E[a+2]=b.screenX;E[a+3]=b.screenY;E[a+4]=b.clientX;E[a+5]=b.clientY;E[a+6]=b.ctrlKey;E[a+7]=b.shiftKey;E[a+8]=b.altKey;E[a+9]=b.metaKey;pa[2*a+20]=b.button;pa[2*a+21]=b.buttons;E[a+11]=b.movementX;E[a+12]=b.movementY;c=Ta(c);E[a+13]=b.clientX-c.left;E[a+14]=b.clientY-c.top}
function S(a,b,c,d,f,h){P||(P=R(72));a=Q(a);O({target:a,Ib:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Bb:h,Db:d,Eb:function(g){g=g||event;Wa(P,g,a);L(d)(f,P,b)&&g.preventDefault()},Cb:c})}function T(a,b,c,d,f){Oa||(Oa=R(260));O({target:a,Bb:f,Db:d,Eb:function(h){h=h||event;var g=Oa,m=document.pointerLockElement||document.Pb||document.Rb||document.Qb;E[g>>2]=!!m;var n=m&&m.id?m.id:"";B(La(m),g+4,128);B(n,g+132,128);L(d)(20,g,b)&&h.preventDefault()},Cb:c})}
function Xa(a,b,c,d,f){O({target:a,Bb:f,Db:d,Eb:function(h){h=h||event;L(d)(38,0,b)&&h.preventDefault()},Cb:c})}
function Ya(a,b,c,d){Pa||(Pa=R(36));a=Q(a);O({target:a,Bb:"resize",Db:d,Eb:function(f){f=f||event;if(f.target==a){var h=document.body;if(h){var g=Pa;E[g>>2]=f.detail;E[g+4>>2]=h.clientWidth;E[g+8>>2]=h.clientHeight;E[g+12>>2]=innerWidth;E[g+16>>2]=innerHeight;E[g+20>>2]=outerWidth;E[g+24>>2]=outerHeight;E[g+28>>2]=pageXOffset;E[g+32>>2]=pageYOffset;L(d)(10,g,b)&&f.preventDefault()}}},Cb:c})}
function Za(a,b,c,d,f,h){Qa||(Qa=R(1696));a=Q(a);O({target:a,Ib:"touchstart"==h||"touchend"==h,Bb:h,Db:d,Eb:function(g){for(var m,n={},p=g.touches,r=0;r<p.length;++r)m=p[r],m.Ub=m.Vb=0,n[m.identifier]=m;for(r=0;r<g.changedTouches.length;++r)m=g.changedTouches[r],m.Ub=1,n[m.identifier]=m;for(r=0;r<g.targetTouches.length;++r)n[g.targetTouches[r].identifier].Vb=1;p=Qa;F[p>>3]=g.timeStamp;var q=p>>2;E[q+3]=g.ctrlKey;E[q+4]=g.shiftKey;E[q+5]=g.altKey;E[q+6]=g.metaKey;q+=7;var J=Ta(a),cb=0;for(r in n)if(m=
n[r],E[q]=m.identifier,E[q+1]=m.screenX,E[q+2]=m.screenY,E[q+3]=m.clientX,E[q+4]=m.clientY,E[q+5]=m.pageX,E[q+6]=m.pageY,E[q+7]=m.Ub,E[q+8]=m.Vb,E[q+9]=m.clientX-J.left,E[q+10]=m.clientY-J.top,q+=13,31<++cb)break;E[p+8>>2]=cb;L(d)(f,p,b)&&g.preventDefault()},Cb:c})}function $a(a,b,c,d,f,h){a={target:Q(a),Bb:h,Db:d,Eb:function(g){g=g||event;L(d)(f,0,b)&&g.preventDefault()},Cb:c};O(a)}
function ab(a,b,c,d){Ra||(Ra=R(104));O({target:a,Ib:!0,Bb:"wheel",Db:d,Eb:function(f){f=f||event;var h=Ra;Wa(h,f,a);F[h+72>>3]=f.deltaX;F[h+80>>3]=f.deltaY;F[h+88>>3]=f.deltaZ;E[h+96>>2]=f.deltaMode;L(d)(9,h,b)&&f.preventDefault()},Cb:c})}
function bb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,h){b.drawArraysInstancedANGLE(c,d,f,h)},a.drawElementsInstanced=function(c,d,f,h,g){b.drawElementsInstancedANGLE(c,d,f,h,g)})}
function db(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function eb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function fb(a){a.qc=a.getExtension("WEBGL_multi_draw")}
var gb=1,hb=[],U=[],ib=[],V=[],W=[],X=[],jb=[],kb={};function Y(a){lb||(lb=a)}function mb(a){for(var b=gb++,c=a.length;c<b;c++)a[c]=null;return b}function nb(a,b){a.Tb||(a.Tb=a.getContext,a.getContext=function(d,f){f=a.Tb(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?ob(c,b):0}function ob(a,b){var c=mb(jb),d={oc:c,attributes:b,version:b.ic,Mb:a};a.canvas&&(a.canvas.jc=d);jb[c]=d;("undefined"===typeof b.Sb||b.Sb)&&pb(d);return c}
function pb(a){a||(a=qb);if(!a.hc){a.hc=!0;var b=a.Mb;bb(b);db(b);eb(b);b.mc=b.getExtension("EXT_disjoint_timer_query");fb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var lb,qb,rb=["default","low-power","high-performance"];function sb(a,b,c,d){for(var f=0;f<a;f++){var h=Z[c](),g=h&&mb(d);h?(h.name=g,d[g]=h):Y(1282);E[b+4*f>>2]=g}}
function tb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:Y(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)E[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){Y(1280);y("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:Y(1280);y("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}E[b>>2]=c}else Y(1281)}
function ub(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}b+=1;c=R(b);B(a,c,b);return c}function vb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}
var Z,Bb={L:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},da:function(a,b,c){a=Q(a);if(!a)return-4;a=Ta(a);F[b>>3]=a.width;F[c>>3]=a.height;return 0},Za:function(a,b,c){D.copyWithin(a,b,b+c)},Ta:function(a,b){function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ya:function(){A("OOM")},N:function(a,b,c,d){Ua(a,b,c,d,12,"blur");return 0},I:function(a,b,c){a=Q(a);if(!a)return-4;a.width=b;a.height=c;return 0},O:function(a,b,c,d){Ua(a,b,c,d,13,
"focus");return 0},X:function(a,b,c,d){Va(a,b,c,d,2,"keydown");return 0},V:function(a,b,c,d){Va(a,b,c,d,1,"keypress");return 0},W:function(a,b,c,d){Va(a,b,c,d,3,"keyup");return 0},r:function(a,b,c,d){S(a,b,c,d,5,"mousedown");return 0},_:function(a,b,c,d){S(a,b,c,d,33,"mouseenter");return 0},Z:function(a,b,c,d){S(a,b,c,d,34,"mouseleave");return 0},aa:function(a,b,c,d){S(a,b,c,d,8,"mousemove");return 0},ca:function(a,b,c,d){S(a,b,c,d,6,"mouseup");return 0},Q:function(a,b,c,d){if(!document||!document.body||
!(document.body.requestPointerLock||document.body.Pb||document.body.Rb||document.body.Qb))return-1;a=Q(a);if(!a)return-4;T(a,b,c,d,"pointerlockchange");T(a,b,c,d,"mozpointerlockchange");T(a,b,c,d,"webkitpointerlockchange");T(a,b,c,d,"mspointerlockchange");return 0},P:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Pb||document.body.Rb||document.body.Qb))return-1;a=Q(a);if(!a)return-4;Xa(a,b,c,d,"pointerlockerror");Xa(a,b,c,d,"mozpointerlockerror");Xa(a,b,c,d,"webkitpointerlockerror");
Xa(a,b,c,d,"mspointerlockerror");return 0},Xa:function(a,b,c,d){Ya(a,b,c,d);return 0},R:function(a,b,c,d){Za(a,b,c,d,25,"touchcancel");return 0},S:function(a,b,c,d){Za(a,b,c,d,23,"touchend");return 0},T:function(a,b,c,d){Za(a,b,c,d,24,"touchmove");return 0},U:function(a,b,c,d){Za(a,b,c,d,22,"touchstart");return 0},M:function(a,b,c,d){$a(a,b,c,d,31,"webglcontextlost");return 0},K:function(a,b,c,d){$a(a,b,c,d,32,"webglcontextrestored");return 0},Y:function(a,b,c,d){a=Q(a);return"undefined"!==typeof a.onwheel?
(ab(a,b,c,d),0):-1},D:function(a,b){b>>=2;b={alpha:!!E[b],depth:!!E[b+1],stencil:!!E[b+2],antialias:!!E[b+3],premultipliedAlpha:!!E[b+4],preserveDrawingBuffer:!!E[b+5],powerPreference:rb[E[b+6]],failIfMajorPerformanceCaveat:!!E[b+7],ic:E[b+8],pc:E[b+9],Sb:E[b+10],fc:E[b+11],rc:E[b+12],sc:E[b+13]};a=Q(a);return!a||b.fc?0:nb(a,b)},sa:function(a,b){a=jb[a];b=C(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&bb(Z);"OES_vertex_array_object"==b&&db(Z);"WEBGL_draw_buffers"==b&&eb(Z);
"WEBGL_multi_draw"==b&&fb(Z);return!!a.Mb.getExtension(b)},Ha:function(a){a>>=2;for(var b=0;14>b;++b)E[a+b]=0;E[a]=E[a+1]=E[a+3]=E[a+4]=E[a+8]=E[a+10]=1},za:function(a){qb=jb[a];e.lc=Z=qb&&qb.Mb;return!a||Z?0:-5},p:function(a){Z.activeTexture(a)},G:function(a,b){Z.attachShader(U[a],X[b])},b:function(a,b){Z.bindBuffer(a,hb[b])},f:function(a,b){Z.bindFramebuffer(a,ib[b])},La:function(a,b){Z.bindRenderbuffer(a,V[b])},g:function(a,b){Z.bindTexture(a,W[b])},v:function(a,b,c,d){Z.blendColor(a,b,c,d)},w:function(a,
b){Z.blendEquationSeparate(a,b)},x:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},Na:function(a,b,c,d){Z.bufferData(a,c?D.subarray(c,c+b):b,d)},H:function(a,b,c,d){Z.bufferSubData(a,b,D.subarray(d,d+c))},A:function(a){return Z.checkFramebufferStatus(a)},va:function(a){Z.clear(a)},ya:function(a,b,c,d){Z.clearColor(a,b,c,d)},xa:function(a){Z.clearDepth(a)},wa:function(a){Z.clearStencil(a)},h:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},$a:function(a){Z.compileShader(X[a])},Ia:function(a,b,c,d,f,
h,g,m){Z.compressedTexImage2D(a,b,c,d,f,h,m?D.subarray(m,m+g):null)},Fa:function(){var a=mb(U),b=Z.createProgram();b.name=a;b.Lb=b.Jb=b.Kb=0;b.Ob=1;U[a]=b;return a},bb:function(a){var b=mb(X);X[b]=Z.createShader(a);return b},u:function(a){Z.cullFace(a)},Pa:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],f=hb[d];f&&(Z.deleteBuffer(f),f.name=0,hb[d]=null)}},o:function(a,b){for(var c=0;c<a;++c){var d=E[b+4*c>>2],f=ib[d];f&&(Z.deleteFramebuffer(f),f.name=0,ib[d]=null)}},J:function(a){if(a){var b=
U[a];b?(Z.deleteProgram(b),b.name=0,U[a]=null):Y(1281)}},ba:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],f=V[d];f&&(Z.deleteRenderbuffer(f),f.name=0,V[d]=null)}},n:function(a){if(a){var b=X[a];b?(Z.deleteShader(b),X[a]=null):Y(1281)}},eb:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],f=W[d];f&&(Z.deleteTexture(f),f.name=0,W[d]=null)}},k:function(a){Z.depthFunc(a)},l:function(a){Z.depthMask(!!a)},a:function(a){Z.disable(a)},s:function(a){Z.disableVertexAttribArray(a)},la:function(a,b,
c){Z.drawArrays(a,b,c)},ma:function(a,b,c,d){Z.drawArraysInstanced(a,b,c,d)},na:function(a,b,c,d){Z.drawElements(a,b,c,d)},oa:function(a,b,c,d,f){Z.drawElementsInstanced(a,b,c,d,f)},d:function(a){Z.enable(a)},pa:function(a){Z.enableVertexAttribArray(a)},m:function(a,b,c,d){Z.framebufferRenderbuffer(a,b,c,V[d])},B:function(a,b,c,d,f){Z.framebufferTexture2D(a,b,c,W[d],f)},t:function(a){Z.frontFace(a)},Oa:function(a,b){sb(a,b,"createBuffer",hb)},C:function(a,b){sb(a,b,"createFramebuffer",ib)},Ma:function(a,
b){sb(a,b,"createRenderbuffer",V)},Ja:function(a,b){sb(a,b,"createTexture",W)},Ba:function(a,b){return Z.getAttribLocation(U[a],C(b))},c:function(a,b){tb(a,b)},Da:function(a,b,c,d){a=Z.getProgramInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,d,b):0;c&&(E[c>>2]=b)},F:function(a,b,c){if(c)if(a>=gb)Y(1281);else if(a=U[a],35716==b)a=Z.getProgramInfoLog(a),null===a&&(a="(unknown error)"),E[c>>2]=a.length+1;else if(35719==b){if(!a.Lb)for(b=0;b<Z.getProgramParameter(a,35718);++b)a.Lb=Math.max(a.Lb,
Z.getActiveUniform(a,b).name.length+1);E[c>>2]=a.Lb}else if(35722==b){if(!a.Jb)for(b=0;b<Z.getProgramParameter(a,35721);++b)a.Jb=Math.max(a.Jb,Z.getActiveAttrib(a,b).name.length+1);E[c>>2]=a.Jb}else if(35381==b){if(!a.Kb)for(b=0;b<Z.getProgramParameter(a,35382);++b)a.Kb=Math.max(a.Kb,Z.getActiveUniformBlockName(a,b).length+1);E[c>>2]=a.Kb}else E[c>>2]=Z.getProgramParameter(a,b);else Y(1281)},_a:function(a,b,c,d){a=Z.getShaderInfoLog(X[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,d,b):0;c&&(E[c>>
2]=b)},$:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(X[a]),null===a&&(a="(unknown error)"),E[c>>2]=a?a.length+1:0):35720==b?(a=Z.getShaderSource(X[a]),E[c>>2]=a?a.length+1:0):E[c>>2]=Z.getShaderParameter(X[a],b):Y(1281)},Qa:function(a){var b=kb[a];if(!b){switch(a){case 7939:b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=ub(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||Y(1280);b=b&&ub(b);break;case 7938:b=ub("OpenGL ES 2.0 ("+
Z.getParameter(7938)+")");break;case 35724:b=Z.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ub(b);break;default:Y(1280)}kb[a]=b}return b},E:function(a,b){b=C(b);if(a=U[a]){var c=a,d=c.Hb,f=c.cc,h;if(!d)for(c.Hb=d={},c.bc={},h=0;h<Z.getProgramParameter(c,35718);++h){var g=Z.getActiveUniform(c,h);var m=g.name;g=g.size;var n=vb(m);n=0<n?m.slice(0,n):m;var p=c.Ob;c.Ob+=g;f[n]=[g,p];for(m=
0;m<g;++m)d[p]=m,c.bc[p++]=n}c=a.Hb;d=0;f=b;h=vb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,f=b.slice(0,h));if((f=a.cc[f])&&d<f[0]&&(d+=f[1],c[d]=c[d]||Z.getUniformLocation(a,b)))return d}else Y(1281);return-1},Ea:function(a){a=U[a];Z.linkProgram(a);a.Hb=0;a.cc={}},y:function(a,b){Z.polygonOffset(a,b)},Ka:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},Aa:function(a,b,c,d){Z.scissor(a,b,c,d)},ab:function(a,b,c,d){for(var f="",h=0;h<b;++h){var g=d?E[d+4*h>>2]:-1;f+=C(E[c+4*h>>2],0>g?void 0:g)}Z.shaderSource(X[a],
f)},db:function(a,b,c){Z.stencilFunc(a,b,c)},ua:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},j:function(a){Z.stencilMask(a)},cb:function(a,b,c){Z.stencilOp(a,b,c)},ta:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},Ga:function(a,b,c,d,f,h,g,m,n){var p=Z,r=p.texImage2D;if(n){var q=m-5120;q=1==q?D:4==q?E:6==q?sa:5==q||28922==q?ra:qa;var J=31-Math.clz32(q.BYTES_PER_ELEMENT);n=q.subarray(n>>J,n+f*(d*({5:3,6:4,8:2,29502:3,29504:4}[g-6402]||1)*(1<<J)+4-1&-4)>>J)}else n=null;r.call(p,a,b,c,d,f,h,g,
m,n)},e:function(a,b,c){Z.texParameteri(a,b,c)},Ca:function(a,b){var c=Z,d=c.uniform1i;var f=Z.dc;if(f){var h=f.Hb[a];"number"===typeof h&&(f.Hb[a]=h=Z.getUniformLocation(f,f.bc[a]+(0<h?"["+h+"]":"")));a=h}else Y(1282),a=void 0;d.call(c,a,b)},i:function(a){a=U[a];Z.useProgram(a);Z.dc=a},qa:function(a,b){Z.vertexAttribDivisor(a,b)},ra:function(a,b,c,d,f,h){Z.vertexAttribPointer(a,b,c,!!d,f,h)},z:function(a,b,c,d){Z.viewport(a,b,c,d)},Wa:function(){e.Wb=function(a){0!=wb()&&(a.preventDefault(),a.returnValue=
" ")};window.addEventListener("beforeunload",e.Wb)},Va:function(){e.ac=function(a){a=a.clipboardData.getData("text");ja("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",e.ac)},Ua:function(a){e.tc=[];a=C(a);a=document.getElementById(a);e.Xb=function(b){b.stopPropagation();b.preventDefault()};e.Yb=function(b){b.stopPropagation();b.preventDefault()};e.Zb=function(b){b.stopPropagation();b.preventDefault()};e.$b=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;
e.uc=c;xb(c.length);var d;for(d=0;d<c.length;d++)ja("_sapp_emsc_drop",["number","string"],[d,c[d].name]);yb(b.clientX,b.clientY)};a.addEventListener("dragenter",e.Xb,!1);a.addEventListener("dragleave",e.Yb,!1);a.addEventListener("dragover",e.Zb,!1);a.addEventListener("drop",e.$b,!1)},Sa:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},hb:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";
a.addEventListener("focusout",function(){zb()});document.body.append(a)},gb:function(){document.getElementById("_sokol_app_input_element").focus()},ib:function(a){a=C(a);e.Gb=document.getElementById(a);e.Gb||console.log("sokol_app.h: invalid target:"+a);e.Gb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},ga:function(){window.removeEventListener("beforeunload",e.Wb)},fa:function(){window.removeEventListener("paste",e.ac)},ea:function(a){a=C(a);a=document.getElementById(a);
a.removeEventListener("dragenter",e.Xb);a.removeEventListener("dragleave",e.Yb);a.removeEventListener("dragover",e.Zb);a.removeEventListener("drop",e.$b)},q:function(){e.Gb&&e.Gb.requestPointerLock&&e.Gb.requestPointerLock()},Ra:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var f=d.getContext("2d"),h=f.createImageData(a,b);h.data.set(D.subarray(c,c+a*b*4));f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();
document.head.appendChild(a)},fb:function(){document.getElementById("_sokol_app_input_element").blur()},ia:function(){return e.Fb?e.Fb.bufferSize:0},ka:function(a,b,c){e.Ab=null;e.Fb=null;"undefined"!==typeof AudioContext?e.Ab=new AudioContext({sampleRate:a,latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?e.Ab=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(e.Ab=null,console.log("sokol_audio.h: no WebAudio support"));return e.Ab?(console.log("sokol_audio.h: sample rate ",
e.Ab.sampleRate),e.Fb=e.Ab.createScriptProcessor(c,0,b),e.Fb.onaudioprocess=function(d){var f=d.outputBuffer.length,h=Ab(f);if(h)for(var g=d.outputBuffer.numberOfChannels,m=0;m<g;m++)for(var n=d.outputBuffer.getChannelData(m),p=0;p<f;p++)n[p]=sa[(h>>2)+(g*p+m)]},e.Fb.connect(e.Ab.destination),a=function(){e.Ab&&"suspended"===e.Ab.state&&e.Ab.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),
1):0},ja:function(){return e.Ab?e.Ab.sampleRate:0},ha:function(){null!==e.Ab&&(e.Fb&&e.Fb.disconnect(),e.Ab.close(),e.Ab=null,e.Fb=null)}};
(function(){function a(f){e.asm=f.exports;ha=e.asm.jb;f=ha.buffer;e.HEAP8=la=new Int8Array(f);e.HEAP16=pa=new Int16Array(f);e.HEAP32=E=new Int32Array(f);e.HEAPU8=D=new Uint8Array(f);e.HEAPU16=qa=new Uint16Array(f);e.HEAPU32=ra=new Uint32Array(f);e.HEAPF32=sa=new Float32Array(f);e.HEAPF64=F=new Float64Array(f);ta=e.asm.mb;va.unshift(e.asm.kb);G--;e.monitorRunDependencies&&e.monitorRunDependencies(G);0==G&&(null!==Aa&&(clearInterval(Aa),Aa=null),H&&(f=H,H=null,f()))}function b(f){a(f.instance)}function c(f){return Ea().then(function(h){return WebAssembly.instantiate(h,
d)}).then(function(h){return h}).then(f,function(h){y("failed to asynchronously prepare wasm: "+h);A(h)})}var d={a:Bb};G++;e.monitorRunDependencies&&e.monitorRunDependencies(G);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return y("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return z||"function"!==typeof WebAssembly.instantiateStreaming||Ba()||I.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(I,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,
d).then(b,function(h){y("wasm streaming compile failed: "+h);y("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.kb).apply(null,arguments)};e._main=function(){return(e._main=e.asm.lb).apply(null,arguments)};var zb=e.__sapp_emsc_notify_keyboard_hidden=function(){return(zb=e.__sapp_emsc_notify_keyboard_hidden=e.asm.nb).apply(null,arguments)};
e.__sapp_emsc_onpaste=function(){return(e.__sapp_emsc_onpaste=e.asm.ob).apply(null,arguments)};var wb=e.__sapp_html5_get_ask_leave_site=function(){return(wb=e.__sapp_html5_get_ask_leave_site=e.asm.pb).apply(null,arguments)},xb=e.__sapp_emsc_begin_drop=function(){return(xb=e.__sapp_emsc_begin_drop=e.asm.qb).apply(null,arguments)};e.__sapp_emsc_drop=function(){return(e.__sapp_emsc_drop=e.asm.rb).apply(null,arguments)};
var yb=e.__sapp_emsc_end_drop=function(){return(yb=e.__sapp_emsc_end_drop=e.asm.sb).apply(null,arguments)};e.__sapp_emsc_invoke_fetch_cb=function(){return(e.__sapp_emsc_invoke_fetch_cb=e.asm.tb).apply(null,arguments)};var R=e._malloc=function(){return(R=e._malloc=e.asm.ub).apply(null,arguments)};e._free=function(){return(e._free=e.asm.vb).apply(null,arguments)};
var Ab=e.__saudio_emsc_pull=function(){return(Ab=e.__saudio_emsc_pull=e.asm.wb).apply(null,arguments)},ma=e.stackSave=function(){return(ma=e.stackSave=e.asm.xb).apply(null,arguments)},na=e.stackRestore=function(){return(na=e.stackRestore=e.asm.yb).apply(null,arguments)},ka=e.stackAlloc=function(){return(ka=e.stackAlloc=e.asm.zb).apply(null,arguments)},Cb;function x(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}H=function Db(){Cb||Eb();Cb||(H=Db)};
function Eb(){function a(){if(!Cb&&(Cb=!0,e.calledRun=!0,!ia)){K(va);K(wa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Fb){var b=e._main;try{var c=b(0,0);if(!(noExitRuntime||0<fa)){if(e.onExit)e.onExit(c);ia=!0}k(c,new x(c))}catch(d){d instanceof x||"unwind"==d||k(1,d)}finally{}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)b=e.postRun.shift(),ya.unshift(b);K(ya)}}if(!(0<G)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)za();
K(ua);0<G||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=Eb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Fb=!0;e.noInitialRun&&(Fb=!1);Eb();
